# Generated by Django 3.2.6 on 2021-08-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Company_HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_Hr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_hr',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.CharField(default=0, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('company_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company_hr')),
            ],
            options={
                'db_table': 'purchase_request',
            },
        ),
        migrations.CreateModel(
            name='Consumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumed', models.CharField(default=0, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('company_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company_hr')),
            ],
            options={
                'db_table': 'consume_request',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabel', models.CharField(default=0, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('company_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company_hr')),
            ],
            options={
                'db_table': 'availabe_request',
            },
        ),
        migrations.CreateModel(
            name='ApiCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.available')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('company_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company_hr')),
                ('consumed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.consumed')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.purchase')),
            ],
            options={
                'db_table': 'apicount',
            },
        ),
    ]
