# Generated by Django 3.2.6 on 2021-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumed',
            name='today_consumed',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='today_purchase',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
