# Generated by Django 3.2.6 on 2021-09-08 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20210905_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=500, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_branch', models.CharField(blank=True, max_length=500, null=True)),
                ('employee_department', models.CharField(blank=True, max_length=500, null=True)),
                ('employee_cowin_pdf', models.BinaryField()),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('Beneficiary_Id', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('cowin_status', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('does1_date', models.DateField(blank=True, null=True)),
                ('does2_date', models.DateField(blank=True, null=True)),
                ('vaccine', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company')),
                ('company_HR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.company_hr')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profile',
            },
        ),
    ]
