# Generated by Django 3.2.6 on 2021-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_employeeprofile_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_cowin_pdf',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
