# Generated by Django 3.2.6 on 2021-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_employeeprofile_employee_cowin_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
