# Generated by Django 3.2.6 on 2021-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_employeeprofile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='test',
            field=models.TextField(blank=True, db_column='data', null=True),
        ),
    ]
