# Generated by Django 3.2.6 on 2021-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_employeeprofile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(default='favicon.ico', upload_to='images/')),
                ('imgae_b64', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
