# Generated by Django 3.2.6 on 2021-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_name_cowin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
